### ISSUE TITLE
Some "bugs" from an user of BS

### ISSUE THREAD

**Issue by phoenixita** [scotthartbti/android_packages_apps_Settings#10]
Not to sound unrespectful to you. An user for the One S reported some bugs. I supposed this can help you tracking some bugs! I love the rom and I'd like to see it perfect! I'll paste the whole post here:
- "network event notification" does not work. (should display "DIALING (WAITING)" instead of just "DIALING" when calling someone that's already engaged in a call. Also should display "DIVERTED INCOMING CALL" when receiving a call made to a number you own and you have set to divert calls to your actual number)
- changing font size in Settings-Display-Font Size has no effect
- opening a messaging app like Messaging or Whatsapp by tapping on the Halo notification, opens the app in the small window but clicking on the text input field does not open the keyboard. It takes several taps/long taps to open it. Also the "send" arrow does not work to send the whatsapp message or SMS
- the option to keep hardware button light on all the time (in Settings-Buttons), does not work. The light goes off after approx 5 secs regardless of the setting
- in Settings-Battery, the device is shown as "awake" all the time
- when setting a "Custom carrier label" (in Settings-Beanstalk Options-Misc options), the name is shown twice if "show WiFi network name" is active.
- when setting a "Custom carrier label" (in Settings-Beanstalk Options-Misc options), the name is shown in ALL CAPS regardless of the way it's written. (for ex it displays "ASSASSINS" even if it was written as "AssaSsinS"
- there is no "kill app by long press of back button" in either Settings-Buttons or in Developer Options
- "Large text" option in Settings-Accessibility has no effect (related to the "Font size" issue)
- when Active Display is on and receive a notification, in most cases dragging the handle to the left (to open the notifying app), brings first the lock screen instead of directly going to the app.
- when Active Display is on, and the app that generates the notification is open, you cannot type and reply, the text input field is "frozen" (nothing can be typed). You have to press back and close the app completely, then open it again to be able to reply (tested with Messaging/SMS and whatsapp

On another side you should take a look to this commit(fixes a bt car kit issue):
https://android-review.googlesource.com/#/c/48164/
Also my builds are suffering of systemu/i f/c if not dirty flashed over 4.4.008. Here are two olds logcat hope you can help me. 
http://www.mediafire.com/view/sc33bcblea9jigk/systemauifc.txt 
http://www.mediafire.com/view/4xgol3vwq2lnnlg/systemuifc.txt

This was just to inform you! Love the way you created this ROM! Have a nice day! 
-phoenixita

**Comment by scotthartbti** [comment]
Seriously?  Almost everything on that list is the way its supposed to be.  If users want it 100 percent like stock android, you may want to have them stick with a stock android ROM.  Making a list composed of shit that's not even broken is just insulting.  If it bothers you and your users that obviously want everything setup to their liking, then you and your users can make the necesarry changes yourself.  Lastely, if your having trouble with builds you need to reach out to the development building beanstalk webpage.  Sounds like you have something in your device trees that shouldn't be there.

**Comment by phoenixita** [comment]
This was not meant to offend you. Personally i love the way this rom it is! Sorry for the missunderstood.

**Comment by scotthartbti** [comment]
No need for apologies...  I just took a closer look and do see that font
size control is not working properly.  I know it had been previously
working...  Can you get more details from the user that reported that
particular issue?  Like when they noticed it stopped working... even if its
just a rough estimate... anything like that to help narrow down the issue
will be helpful.

**Comment by scotthartbti** [comment]
reopening to fix font control

**Comment by phoenixita** [comment]
I rember on 4.4.200 was working...

**Comment by RapierXDA** [comment]
Well, what can I say. Sarcasm is a very good answer when you have no arguments.  Sometimes I really wish devs like you don;t even exist (as yoy would like that users like me don't exist). You might as well want to be GOD and anyone should raise a statue for your. No one should dare saying something because you're perfect.
You do it for free, right but this not grant you the right to insult. I was pointing out some BUGs...you like it or not they are bugs. As my daily job I manage an IT Quality Control team, I do it for a lot of years and I have several certifications in this field...so I know very well what a bug is, how to track it and how the devs think...I see it everyday. The issues there are not the way I WANT them is the normal way they should work. If you tell me that you have a setting for making the lights on the buttons lit always, but you specifically make it not to work because YOU like it so, that is the most lame excuse I could ever hear.

It's pointless to argue with you. You're right...you build it and do what YOU want. But don't pretend you're perfect because you're far from that. You should learn to listen to those users you hate and have the guts to admit when you're wrong. Obviously this is not your strongest point. It's better to tell that it's intended behaviour of a setting even if that behaviour defies logic and common sense.

Yeah, I know..it's hard to accept someone has dared to criticise your work. I even didn't do that, I said from start I like this ROM...i just pointed out some bugs and you you jumped like I've burned you alive.

Hopefully the ROM will get better with or without your attitude. Don't worry, sit back and relax

**Comment by scotthartbti** [comment]
Are you done yet?  What are you 10 years old?

**Comment by scotthartbti** [comment]
And the issue your talking about with the buttons lit always is something
that is controlled from the device side code and is exactly how CyanogenMod
has it implemented.  The device maintainer needs to add the appropriate
code in his tree genius.

**Comment by RapierXDA** [comment]
No...46 :) You can't just reply like that without expecting me to respond right? Can we grow up now? You misunderstood me from the very first moment, but I don't like this fight. I prefer more to enjoy your ROM. The fact was that, most of the things there were also bugged in all KitKat ROms and if you have solved them, you could have been proud that your ROM has things no other KitKat ROM has. I;m done and really wish to see this ROM go further as it is one of the best I've tried

**Comment by ghost** [comment]
Font Control: I took a quick look and the font size doesn't change when using Accessibility or Display options. There doesn't seem to be an error in logcat but these lines seemed relevant:

I/ActivityManager(  498): Config changes=40000000 {1.3 ?mcc?mnc en_US ldltr sw32
0dp w320dp h508dp 240dpi nrml long port finger -keyb/v/h -nav/h s.30 themeResour
ce=null}

I/ActivityManager(  498): Config changes=40000000 {1.0 ?mcc?mnc en_US ldltr sw32
0dp w320dp h508dp 240dpi nrml long port finger -keyb/v/h -nav/h s.29 themeResour
ce=null}

Those are from tapping "Large Text" in Accessibility. 1.3 and 1.0 Look like the magnification....?

Hope it helps...

**Comment by scotthartbti** [comment]
Thanks for the log... I'm pretty sure I know what caused this issue and
should have something later this evening.

**Comment by scotthartbti** [comment]
Font size issue has been resolved.  Had to revert the change DPI on the fly commit as that was causing the issues.  font size now works under display options and accessibility options (large font).   This was a 3 part revert as follows:

frameworks/native: commit 107c4540681490cd5a8aa3cdeb891e46719d9595
frameworks/base: commit f69da18c915defd4576311f6f5ee4d4cf092140b
packages/apps/Settings: commit e235e8f1e8ccff9befbd7a88750f61c9339d7fad

Oh and i cleaned up the display layout and code to follow CM standards including the CM display rotation implementation.
