### ISSUE TITLE
Settings language is always English, regardless of selected language

### ISSUE THREAD

**Issue by sreinst1** [scotthartbti/android_packages_apps_Settings#7]
The language used by the Settings application is English, no matter which language is selected for the phone.

**Comment by scotthartbti** [comment]
Fixed with commit d80dc74108938dfade2cef84db8fad59aec6907a

**Comment by sreinst1** [comment]
Thanks... It is _mostly_ fixed. I think only menu items that are in the original Android appear in the selected language. Things like "performance control", "lock screen" etc are not.
Is there a way to help you with this? e.g. I use Hebrew, can I send you the Hebrew labels for these, or better, somehow push the translations to your repository? (maybe to a branch)

**Comment by scotthartbti** [comment]
Not to sound rude, but its COMPLETELY fixed.  The reason that some of those items arent translating are because the translations for those items are not defined... Hence the reason you dont see them in your language.  Again, not broken, just not defined.  Everything is working as it should though.  And yes if you want to add the strings for your language i will add them to the settings package.  There are a crap ton of languages available and there is no way id have the time to go and translate every single one of them...

**Comment by sreinst1** [comment]
What's the best way for me to provide my language translations? Do I just
send you a modified version of bs_strings.xml that you will put under
values-iw, or is there a better way?

**Comment by scotthartbti** [comment]
There are a couple ways we can do it...  You can send me a pull request and i can merge it or you can simply push it to your github and let me know and ill go in and cherry-pick it from there.  If your not sure how to open a pull request, there are some helpful guides out there just a google search away

**Comment by sreinst1** [comment]
I'm sorry about that, but I prepared some translation for the Settings app.
However, I tried it, and it looks awful, better stick with the English
version :-)
Anyway, if you'd like help with Hebrew translation of whatever app, let me
know and I'll gladly do the translation.
